//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Document_Maker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAvailableDocumentCreationSoftware {
            get {
                return ((bool)(this["IsAvailableDocumentCreationSoftware"]));
            }
            set {
                this["IsAvailableDocumentCreationSoftware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsWindowsStartUpRunForDCMK {
            get {
                return ((bool)(this["IsWindowsStartUpRunForDCMK"]));
            }
            set {
                this["IsWindowsStartUpRunForDCMK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2010Blue")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SendingDepartment {
            get {
                return ((string)(this["SendingDepartment"]));
            }
            set {
                this["SendingDepartment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string To_CompanyOrOrganizationName {
            get {
                return ((string)(this["To_CompanyOrOrganizationName"]));
            }
            set {
                this["To_CompanyOrOrganizationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string To_Title {
            get {
                return ((string)(this["To_Title"]));
            }
            set {
                this["To_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_CompanyOrOrganizationName {
            get {
                return ((string)(this["Caller_CompanyOrOrganizationName"]));
            }
            set {
                this["Caller_CompanyOrOrganizationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_Location {
            get {
                return ((string)(this["Caller_Location"]));
            }
            set {
                this["Caller_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_BuildingName {
            get {
                return ((string)(this["Caller_BuildingName"]));
            }
            set {
                this["Caller_BuildingName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Caller_FloorNumber {
            get {
                return ((int)(this["Caller_FloorNumber"]));
            }
            set {
                this["Caller_FloorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_Title {
            get {
                return ((string)(this["Caller_Title"]));
            }
            set {
                this["Caller_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string To_Name {
            get {
                return ((string)(this["To_Name"]));
            }
            set {
                this["To_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_Name {
            get {
                return ((string)(this["Caller_Name"]));
            }
            set {
                this["Caller_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_MailAddress_User {
            get {
                return ((string)(this["Caller_MailAddress_User"]));
            }
            set {
                this["Caller_MailAddress_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_MailAddress_Domain {
            get {
                return ((string)(this["Caller_MailAddress_Domain"]));
            }
            set {
                this["Caller_MailAddress_Domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_PhoneNumber1 {
            get {
                return ((string)(this["Caller_PhoneNumber1"]));
            }
            set {
                this["Caller_PhoneNumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_PhoneNumber2 {
            get {
                return ((string)(this["Caller_PhoneNumber2"]));
            }
            set {
                this["Caller_PhoneNumber2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_PhoneNumber3 {
            get {
                return ((string)(this["Caller_PhoneNumber3"]));
            }
            set {
                this["Caller_PhoneNumber3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_FaxNumber1 {
            get {
                return ((string)(this["Caller_FaxNumber1"]));
            }
            set {
                this["Caller_FaxNumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_FaxNumber2 {
            get {
                return ((string)(this["Caller_FaxNumber2"]));
            }
            set {
                this["Caller_FaxNumber2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Caller_FaxNumber3 {
            get {
                return ((string)(this["Caller_FaxNumber3"]));
            }
            set {
                this["Caller_FaxNumber3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseEraName {
            get {
                return ((bool)(this["IsUseEraName"]));
            }
            set {
                this["IsUseEraName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAutoFillContent {
            get {
                return ((bool)(this["UseAutoFillContent"]));
            }
            set {
                this["UseAutoFillContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Space_Top {
            get {
                return ((int)(this["Space_Top"]));
            }
            set {
                this["Space_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Space_Buttom {
            get {
                return ((int)(this["Space_Buttom"]));
            }
            set {
                this["Space_Buttom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int Space_Left {
            get {
                return ((int)(this["Space_Left"]));
            }
            set {
                this["Space_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int Space_Right {
            get {
                return ((int)(this["Space_Right"]));
            }
            set {
                this["Space_Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UseDocumentCreationSoftware {
            get {
                return ((string)(this["UseDocumentCreationSoftware"]));
            }
            set {
                this["UseDocumentCreationSoftware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseBackgroundAppUpdate {
            get {
                return ((bool)(this["UseBackgroundAppUpdate"]));
            }
            set {
                this["UseBackgroundAppUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Notepad_Message_Show {
            get {
                return ((bool)(this["Notepad_Message_Show"]));
            }
            set {
                this["Notepad_Message_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Contact_NavigationBarMode {
            get {
                return ((string)(this["Contact_NavigationBarMode"]));
            }
            set {
                this["Contact_NavigationBarMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT1_Visible {
            get {
                return ((bool)(this["QAT1_Visible"]));
            }
            set {
                this["QAT1_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT2_Visible {
            get {
                return ((bool)(this["QAT2_Visible"]));
            }
            set {
                this["QAT2_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT3_Visible {
            get {
                return ((bool)(this["QAT3_Visible"]));
            }
            set {
                this["QAT3_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT4_Visible {
            get {
                return ((bool)(this["QAT4_Visible"]));
            }
            set {
                this["QAT4_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT5_Visible {
            get {
                return ((bool)(this["QAT5_Visible"]));
            }
            set {
                this["QAT5_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT6_Visible {
            get {
                return ((bool)(this["QAT6_Visible"]));
            }
            set {
                this["QAT6_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT7_Visible {
            get {
                return ((bool)(this["QAT7_Visible"]));
            }
            set {
                this["QAT7_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT8_Visible {
            get {
                return ((bool)(this["QAT8_Visible"]));
            }
            set {
                this["QAT8_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShowApplicationTask {
            get {
                return ((int)(this["ShowApplicationTask"]));
            }
            set {
                this["ShowApplicationTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotepadWarningPanel {
            get {
                return ((bool)(this["ShowNotepadWarningPanel"]));
            }
            set {
                this["ShowNotepadWarningPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowResetDialog {
            get {
                return ((bool)(this["ShowResetDialog"]));
            }
            set {
                this["ShowResetDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dCW_TopSpace {
            get {
                return ((int)(this["dCW_TopSpace"]));
            }
            set {
                this["dCW_TopSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dCW_ButtomSpace {
            get {
                return ((int)(this["dCW_ButtomSpace"]));
            }
            set {
                this["dCW_ButtomSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dCW_LeftSpace {
            get {
                return ((int)(this["dCW_LeftSpace"]));
            }
            set {
                this["dCW_LeftSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dCW_RightSpace {
            get {
                return ((int)(this["dCW_RightSpace"]));
            }
            set {
                this["dCW_RightSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ToOrCaller {
            get {
                return ((int)(this["ToOrCaller"]));
            }
            set {
                this["ToOrCaller"] = value;
            }
        }
    }
}
